stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "docker.io/${REGISTRY_USER}/myapp:latest"  # Docker Hub image name

before_script:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin  # Login to Docker Hub

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

# deploy:
#   stage: deploy
#   image: alpine:latest
#   before_script:
#     - apk add --no-cache openssh-client
#   script:
#     - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
#       docker pull $IMAGE_NAME
#       docker stop myapp || true
#       docker rm myapp || true
#       docker run -d --name myapp -p 8080:80 $IMAGE_NAME
#       EOF
#   only:
#     - main
