<?php

function getVisIpAddr() { 
        
    if (!empty($_SERVER['HTTP_CLIENT_IP'])) { 
        return $_SERVER['HTTP_CLIENT_IP']; 
    } 
    else if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) { 
        return $_SERVER['HTTP_X_FORWARDED_FOR']; 
    } 
    else { 
        return $_SERVER['REMOTE_ADDR']; 
    } 
} 


class ListPays
{
    public const LIST_PAYS = array(
        array(
            "name_fr" => "Afghanistan",
            "name_en" => "Afghanistan",
            "code_iso_2" => "AF",
            "code_iso_3" => "AFG",
            "code_numeric" => "004",
            "code_telephone" => "93",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:25",
            "updated_at" => "2022-07-26 07:33:08",
        ),
        array(
            "name_fr" => "Albanie",
            "name_en" => "Albania",
            "code_iso_2" => "AL",
            "code_iso_3" => "ALB",
            "code_numeric" => "008",
            "code_telephone" => "355",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:25",
            "updated_at" => "2022-07-26 07:24:25",
        ),
        array(
            "name_fr" => "Antarctique",
            "name_en" => "Antarctica",
            "code_iso_2" => "AQ",
            "code_iso_3" => "ATA",
            "code_numeric" => "010",
            "code_telephone" => "672",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:25",
            "updated_at" => "2022-07-26 07:24:25",
        ),
        array(
            "name_fr" => "Algérie",
            "name_en" => "Algeria",
            "code_iso_2" => "DZ",
            "code_iso_3" => "DZA",
            "code_numeric" => "012",
            "code_telephone" => "213",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Samoa américaines",
            "name_en" => "American Samoa",
            "code_iso_2" => "AS",
            "code_iso_3" => "ASM",
            "code_numeric" => "016",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Andorre",
            "name_en" => "Andorra",
            "code_iso_2" => "AD",
            "code_iso_3" => "AND",
            "code_numeric" => "020",
            "code_telephone" => "376",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Angola",
            "name_en" => "Angola",
            "code_iso_2" => "AO",
            "code_iso_3" => "AGO",
            "code_numeric" => "024",
            "code_telephone" => "244",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:32:59",
        ),
        array(
            "name_fr" => "Antigua-et-Barbuda",
            "name_en" => "Antigua and Barbuda",
            "code_iso_2" => "AG",
            "code_iso_3" => "ATG",
            "code_numeric" => "028",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Azerbaïdjan",
            "name_en" => "Azerbaijan",
            "code_iso_2" => "AZ",
            "code_iso_3" => "AZE",
            "code_numeric" => "031",
            "code_telephone" => "994",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Argentine",
            "name_en" => "Argentina",
            "code_iso_2" => "AR",
            "code_iso_3" => "ARG",
            "code_numeric" => "032",
            "code_telephone" => "54",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Australie",
            "name_en" => "Australia",
            "code_iso_2" => "AU",
            "code_iso_3" => "AUS",
            "code_numeric" => "036",
            "code_telephone" => "61",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Autriche",
            "name_en" => "Austria",
            "code_iso_2" => "AT",
            "code_iso_3" => "AUT",
            "code_numeric" => "040",
            "code_telephone" => "43",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Bahamas",
            "name_en" => "Bahamas",
            "code_iso_2" => "BS",
            "code_iso_3" => "BHS",
            "code_numeric" => "044",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Bahreïn",
            "name_en" => "Bahrain",
            "code_iso_2" => "BH",
            "code_iso_3" => "BHR",
            "code_numeric" => "048",
            "code_telephone" => "973",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Bangladesh",
            "name_en" => "Bangladesh",
            "code_iso_2" => "BD",
            "code_iso_3" => "BGD",
            "code_numeric" => "050",
            "code_telephone" => "880",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Arménie",
            "name_en" => "Armenia",
            "code_iso_2" => "AM",
            "code_iso_3" => "ARM",
            "code_numeric" => "051",
            "code_telephone" => "51",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Barbade",
            "name_en" => "Babados",
            "code_iso_2" => "BB",
            "code_iso_3" => "BRB",
            "code_numeric" => "052",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Belgique",
            "name_en" => "Belgium",
            "code_iso_2" => "BE",
            "code_iso_3" => "BEL",
            "code_numeric" => "056",
            "code_telephone" => "32",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:26",
            "updated_at" => "2022-07-26 07:24:26",
        ),
        array(
            "name_fr" => "Bermudes",
            "name_en" => "Bermuda",
            "code_iso_2" => "BM",
            "code_iso_3" => "BMU",
            "code_numeric" => "060",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Bhoutan",
            "name_en" => "Bhutan",
            "code_iso_2" => "BT",
            "code_iso_3" => "BTN",
            "code_numeric" => "064",
            "code_telephone" => "975",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Bolivie",
            "name_en" => "Bolivia",
            "code_iso_2" => "BO",
            "code_iso_3" => "BOL",
            "code_numeric" => "068",
            "code_telephone" => "591",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Bosnie-Herzégovine",
            "name_en" => "Bosnia and Herzegovina",
            "code_iso_2" => "BA",
            "code_iso_3" => "BIH",
            "code_numeric" => "070",
            "code_telephone" => "70",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Botswana",
            "name_en" => "Botswana",
            "code_iso_2" => "BW",
            "code_iso_3" => "BWA",
            "code_numeric" => "072",
            "code_telephone" => "267",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Bouvet",
            "name_en" => "Bouvet Island",
            "code_iso_2" => "BV",
            "code_iso_3" => "BVT",
            "code_numeric" => "074",
            "code_telephone" => "47",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Brésil",
            "name_en" => "Brazil",
            "code_iso_2" => "BR",
            "code_iso_3" => "BRA",
            "code_numeric" => "076",
            "code_telephone" => "76",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Belize",
            "name_en" => "Belize",
            "code_iso_2" => "BZ",
            "code_iso_3" => "BLZ",
            "code_numeric" => "084",
            "code_telephone" => "501",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Indien",
            "name_en" => "British Indian Ocean Territory",
            "code_iso_2" => "IO",
            "code_iso_3" => "IOT",
            "code_numeric" => "086",
            "code_telephone" => "246",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Salomon",
            "name_en" => "Solomon Islands",
            "code_iso_2" => "SB",
            "code_iso_3" => "SLB",
            "code_numeric" => "090",
            "code_telephone" => "90",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Vierges britanniques",
            "name_en" => "Virgin Islands",
            "code_iso_2" => "VG",
            "code_iso_3" => "VGB",
            "code_numeric" => "092",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Brunéi Darussalam",
            "name_en" => "Brunei Darussalam",
            "code_iso_2" => "BN",
            "code_iso_3" => "BRN",
            "code_numeric" => "096",
            "code_telephone" => "96",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Bulgarie",
            "name_en" => "Bulgaria",
            "code_iso_2" => "BG",
            "code_iso_3" => "BGR",
            "code_numeric" => "100",
            "code_telephone" => "359",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Myanmar",
            "name_en" => "Myanmar",
            "code_iso_2" => "MM",
            "code_iso_3" => "MMR",
            "code_numeric" => "104",
            "code_telephone" => "95",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Burundi",
            "name_en" => "Burundi",
            "code_iso_2" => "BI",
            "code_iso_3" => "BDI",
            "code_numeric" => "108",
            "code_telephone" => "257",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:27",
            "updated_at" => "2022-07-26 07:24:27",
        ),
        array(
            "name_fr" => "Bélarus",
            "name_en" => "Belarus",
            "code_iso_2" => "BY",
            "code_iso_3" => "BLR",
            "code_numeric" => "112",
            "code_telephone" => "375",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Cambodge",
            "name_en" => "Cambodia",
            "code_iso_2" => "KH",
            "code_iso_3" => "KHM",
            "code_numeric" => "116",
            "code_telephone" => "855",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Cameroun",
            "name_en" => "Cameroon",
            "code_iso_2" => "CM",
            "code_iso_3" => "CMR",
            "code_numeric" => "120",
            "code_telephone" => "237",
            "active" => 1,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Canada",
            "name_en" => "Canada",
            "code_iso_2" => "CA",
            "code_iso_3" => "CAN",
            "code_numeric" => "124",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Cabo Verde",
            "name_en" => "Cabo Verde",
            "code_iso_2" => "CV",
            "code_iso_3" => "CPV",
            "code_numeric" => "132",
            "code_telephone" => "238",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Caïmans",
            "name_en" => "Cayman Islands",
            "code_iso_2" => "KY",
            "code_iso_3" => "CYM",
            "code_numeric" => "136",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "République centrafricaine",
            "name_en" => "Central African Republic",
            "code_iso_2" => "CF",
            "code_iso_3" => "CAF",
            "code_numeric" => "140",
            "code_telephone" => "236",
            "active" => 1,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Sri Lanka",
            "name_en" => "Sri Lanka",
            "code_iso_2" => "LK",
            "code_iso_3" => "LKA",
            "code_numeric" => "144",
            "code_telephone" => "94",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Tchad",
            "name_en" => "Chad",
            "code_iso_2" => "TD",
            "code_iso_3" => "TCD",
            "code_numeric" => "148",
            "code_telephone" => "235",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Chili",
            "name_en" => "Chile",
            "code_iso_2" => "CL",
            "code_iso_3" => "CHL",
            "code_numeric" => "152",
            "code_telephone" => "56",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Chine",
            "name_en" => "China",
            "code_iso_2" => "CN",
            "code_iso_3" => "CHN",
            "code_numeric" => "156",
            "code_telephone" => "86",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Taïwan",
            "name_en" => "Taiwan",
            "code_iso_2" => "TW",
            "code_iso_3" => "TWN",
            "code_numeric" => "158",
            "code_telephone" => "886",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Christmas",
            "name_en" => "Christmas Island",
            "code_iso_2" => "CX",
            "code_iso_3" => "CXR",
            "code_numeric" => "162",
            "code_telephone" => "61",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:28",
            "updated_at" => "2022-07-26 07:24:28",
        ),
        array(
            "name_fr" => "Cocos/Keeling",
            "name_en" => "Cocos/Keeling Islands",
            "code_iso_2" => "CC",
            "code_iso_3" => "CCK",
            "code_numeric" => "166",
            "code_telephone" => "891",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Colombie",
            "name_en" => "Colombia",
            "code_iso_2" => "CO",
            "code_iso_3" => "COL",
            "code_numeric" => "170",
            "code_telephone" => "57",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Comores",
            "name_en" => "Comoros",
            "code_iso_2" => "KM",
            "code_iso_3" => "COM",
            "code_numeric" => "174",
            "code_telephone" => "269",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Mayotte",
            "name_en" => "Mayotte",
            "code_iso_2" => "YT",
            "code_iso_3" => "MYT",
            "code_numeric" => "175",
            "code_telephone" => "262",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Congo",
            "name_en" => "Congo",
            "code_iso_2" => "CG",
            "code_iso_3" => "COG",
            "code_numeric" => "178",
            "code_telephone" => "236",
            "active" => 1,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Congo RD",
            "name_en" => "Congo DR",
            "code_iso_2" => "CD",
            "code_iso_3" => "COD",
            "code_numeric" => "180",
            "code_telephone" => "243",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Cook",
            "name_en" => "Cook Islands",
            "code_iso_2" => "CK",
            "code_iso_3" => "COK",
            "code_numeric" => "184",
            "code_telephone" => "682",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Costa Rica",
            "name_en" => "Costa Rica",
            "code_iso_2" => "CR",
            "code_iso_3" => "CRI",
            "code_numeric" => "188",
            "code_telephone" => "506",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Croatie",
            "name_en" => "Croatia",
            "code_iso_2" => "HR",
            "code_iso_3" => "HRV",
            "code_numeric" => "191",
            "code_telephone" => "385",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Cuba",
            "name_en" => "Cuba",
            "code_iso_2" => "CU",
            "code_iso_3" => "CUB",
            "code_numeric" => "192",
            "code_telephone" => "53",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Chypre",
            "name_en" => "Cyprus",
            "code_iso_2" => "CY",
            "code_iso_3" => "CYP",
            "code_numeric" => "196",
            "code_telephone" => "357",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Tchéquie",
            "name_en" => "Czechia",
            "code_iso_2" => "CZ",
            "code_iso_3" => "CZE",
            "code_numeric" => "203",
            "code_telephone" => "420",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Bénin",
            "name_en" => "Benin",
            "code_iso_2" => "BJ",
            "code_iso_3" => "BEN",
            "code_numeric" => "204",
            "code_telephone" => "229",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Danemark",
            "name_en" => "Denmark",
            "code_iso_2" => "DK",
            "code_iso_3" => "DNK",
            "code_numeric" => "208",
            "code_telephone" => "45",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Dominique",
            "name_en" => "Dominica",
            "code_iso_2" => "DM",
            "code_iso_3" => "DMA",
            "code_numeric" => "212",
            "code_telephone" => "767",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Dominicaine",
            "name_en" => "Dominican Republic",
            "code_iso_2" => "DO",
            "code_iso_3" => "DOM",
            "code_numeric" => "214",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "Équateur",
            "name_en" => "Ecuador",
            "code_iso_2" => "EC",
            "code_iso_3" => "ECU",
            "code_numeric" => "218",
            "code_telephone" => "593",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:29",
            "updated_at" => "2022-07-26 07:24:29",
        ),
        array(
            "name_fr" => "El Salvador",
            "name_en" => "El Salvador",
            "code_iso_2" => "SV",
            "code_iso_3" => "SLV",
            "code_numeric" => "222",
            "code_telephone" => "503",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Guinée équatoriale",
            "name_en" => "Equatorial Guinea",
            "code_iso_2" => "GQ",
            "code_iso_3" => "GNQ",
            "code_numeric" => "226",
            "code_telephone" => "240",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Éthiopie",
            "name_en" => "Ethiopia",
            "code_iso_2" => "ET",
            "code_iso_3" => "ETH",
            "code_numeric" => "231",
            "code_telephone" => "251",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Érythrée",
            "name_en" => "Eritrea",
            "code_iso_2" => "ER",
            "code_iso_3" => "ERI",
            "code_numeric" => "232",
            "code_telephone" => "232",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Estonie",
            "name_en" => "Estonia",
            "code_iso_2" => "EE",
            "code_iso_3" => "EST",
            "code_numeric" => "233",
            "code_telephone" => "372",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Féroé",
            "name_en" => "Faroe Islands",
            "code_iso_2" => "FO",
            "code_iso_3" => "FRO",
            "code_numeric" => "234",
            "code_telephone" => "298",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Falkland/Malouines",
            "name_en" => "Falkland Islands [Malvinas]",
            "code_iso_2" => "FK",
            "code_iso_3" => "FLK",
            "code_numeric" => "238",
            "code_telephone" => "500",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Géorgie du Sud-et-les Îles Sandwich du Sud",
            "name_en" => "South Georgia and the South Sandwich Islands",
            "code_iso_2" => "GS",
            "code_iso_3" => "SGS",
            "code_numeric" => "239",
            "code_telephone" => "239",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Fidji",
            "name_en" => "Fiji",
            "code_iso_2" => "FJ",
            "code_iso_3" => "FJI",
            "code_numeric" => "242",
            "code_telephone" => "679",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Finlande",
            "name_en" => "Finland",
            "code_iso_2" => "FI",
            "code_iso_3" => "FIN",
            "code_numeric" => "246",
            "code_telephone" => "358",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Åland",
            "name_en" => "Åland Islands",
            "code_iso_2" => "AX",
            "code_iso_3" => "ALA",
            "code_numeric" => "248",
            "code_telephone" => "248",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "France",
            "name_en" => "France",
            "code_iso_2" => "FR",
            "code_iso_3" => "FRA",
            "code_numeric" => "250",
            "code_telephone" => "33",
            "active" => 1,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Guyane française",
            "name_en" => "French Guiana",
            "code_iso_2" => "GF",
            "code_iso_3" => "GUF",
            "code_numeric" => "254",
            "code_telephone" => "224",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Polynésie française",
            "name_en" => "French Polynesia",
            "code_iso_2" => "PF",
            "code_iso_3" => "PYF",
            "code_numeric" => "258",
            "code_telephone" => "689",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Terres australes françaises",
            "name_en" => "French Southern Territories",
            "code_iso_2" => "TF",
            "code_iso_3" => "ATF",
            "code_numeric" => "260",
            "code_telephone" => "262",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:30",
            "updated_at" => "2022-07-26 07:24:30",
        ),
        array(
            "name_fr" => "Djibouti",
            "name_en" => "Djibouti",
            "code_iso_2" => "DJ",
            "code_iso_3" => "DJI",
            "code_numeric" => "262",
            "code_telephone" => "253",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Gabon",
            "name_en" => "Gabon",
            "code_iso_2" => "GA",
            "code_iso_3" => "GAB",
            "code_numeric" => "266",
            "code_telephone" => "241",
            "active" => 1,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Géorgie",
            "name_en" => "Georgia",
            "code_iso_2" => "GE",
            "code_iso_3" => "GEO",
            "code_numeric" => "268",
            "code_telephone" => "995",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Gambie",
            "name_en" => "Gambia",
            "code_iso_2" => "GM",
            "code_iso_3" => "GMB",
            "code_numeric" => "270",
            "code_telephone" => "220",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Palestine, État de",
            "name_en" => "Palestine, State of",
            "code_iso_2" => "PS",
            "code_iso_3" => "PSE",
            "code_numeric" => "275",
            "code_telephone" => "970",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Allemagne",
            "name_en" => "Germany",
            "code_iso_2" => "DE",
            "code_iso_3" => "DEU",
            "code_numeric" => "276",
            "code_telephone" => "49",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Ghana",
            "name_en" => "Ghana",
            "code_iso_2" => "GH",
            "code_iso_3" => "GHA",
            "code_numeric" => "288",
            "code_telephone" => "233",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Gibraltar",
            "name_en" => "Gibraltar",
            "code_iso_2" => "GI",
            "code_iso_3" => "GIB",
            "code_numeric" => "292",
            "code_telephone" => "350",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Kiribati",
            "name_en" => "Kiribati",
            "code_iso_2" => "KI",
            "code_iso_3" => "KIR",
            "code_numeric" => "296",
            "code_telephone" => "686",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Grèce",
            "name_en" => "Greece",
            "code_iso_2" => "GR",
            "code_iso_3" => "GRC",
            "code_numeric" => "300",
            "code_telephone" => "30",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:31",
            "updated_at" => "2022-07-26 07:24:31",
        ),
        array(
            "name_fr" => "Groenland",
            "name_en" => "Greenland",
            "code_iso_2" => "GL",
            "code_iso_3" => "GRL",
            "code_numeric" => "304",
            "code_telephone" => "299",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:32",
            "updated_at" => "2022-07-26 07:24:32",
        ),
        array(
            "name_fr" => "Grenade",
            "name_en" => "Grenada",
            "code_iso_2" => "GD",
            "code_iso_3" => "GRD",
            "code_numeric" => "308",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:32",
            "updated_at" => "2022-07-26 07:24:32",
        ),
        array(
            "name_fr" => "Guadeloupe",
            "name_en" => "Guadeloupe",
            "code_iso_2" => "GP",
            "code_iso_3" => "GLP",
            "code_numeric" => "312",
            "code_telephone" => "590",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:32",
            "updated_at" => "2022-07-26 07:24:32",
        ),
        array(
            "name_fr" => "Guam",
            "name_en" => "Guam",
            "code_iso_2" => "GU",
            "code_iso_3" => "GUM",
            "code_numeric" => "316",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:32",
            "updated_at" => "2022-07-26 07:24:32",
        ),
        array(
            "name_fr" => "Guatemala",
            "name_en" => "Guatemala",
            "code_iso_2" => "GT",
            "code_iso_3" => "GTM",
            "code_numeric" => "320",
            "code_telephone" => "502",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:32",
            "updated_at" => "2022-07-26 07:24:32",
        ),
        array(
            "name_fr" => "Guinée",
            "name_en" => "Guinea",
            "code_iso_2" => "GN",
            "code_iso_3" => "GIN",
            "code_numeric" => "324",
            "code_telephone" => "224",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:32",
            "updated_at" => "2022-07-26 07:24:32",
        ),
        array(
            "name_fr" => "Guyana",
            "name_en" => "Guyana",
            "code_iso_2" => "GY",
            "code_iso_3" => "GUY",
            "code_numeric" => "328",
            "code_telephone" => "592",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Haïti",
            "name_en" => "Haiti",
            "code_iso_2" => "HT",
            "code_iso_3" => "HTI",
            "code_numeric" => "332",
            "code_telephone" => "509",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Heard-et-Îles MacDonald",
            "name_en" => "Heard Island and McDonald Islands",
            "code_iso_2" => "HM",
            "code_iso_3" => "HMD",
            "code_numeric" => "334",
            "code_telephone" => "61",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Saint-Siège",
            "name_en" => "Holy See",
            "code_iso_2" => "VA",
            "code_iso_3" => "VAT",
            "code_numeric" => "336",
            "code_telephone" => "379",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Honduras",
            "name_en" => "Honduras",
            "code_iso_2" => "HN",
            "code_iso_3" => "HND",
            "code_numeric" => "340",
            "code_telephone" => "504",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Hong Kong",
            "name_en" => "Hong Kong",
            "code_iso_2" => "HK",
            "code_iso_3" => "HKG",
            "code_numeric" => "344",
            "code_telephone" => "852",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Hongrie",
            "name_en" => "Hungary",
            "code_iso_2" => "HU",
            "code_iso_3" => "HUN",
            "code_numeric" => "348",
            "code_telephone" => "36",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Islande",
            "name_en" => "Iceland",
            "code_iso_2" => "IS",
            "code_iso_3" => "ISL",
            "code_numeric" => "352",
            "code_telephone" => "354",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Inde",
            "name_en" => "India",
            "code_iso_2" => "IN",
            "code_iso_3" => "IND",
            "code_numeric" => "356",
            "code_telephone" => "91",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Indonésie",
            "name_en" => "Indonesia",
            "code_iso_2" => "ID",
            "code_iso_3" => "IDN",
            "code_numeric" => "360",
            "code_telephone" => "62",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:33",
            "updated_at" => "2022-07-26 07:24:33",
        ),
        array(
            "name_fr" => "Iran",
            "name_en" => "Iran",
            "code_iso_2" => "IR",
            "code_iso_3" => "IRN",
            "code_numeric" => "364",
            "code_telephone" => "98",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Iraq",
            "name_en" => "Iraq",
            "code_iso_2" => "IQ",
            "code_iso_3" => "IRQ",
            "code_numeric" => "368",
            "code_telephone" => "964",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Irlande",
            "name_en" => "Ireland",
            "code_iso_2" => "IE",
            "code_iso_3" => "IRL",
            "code_numeric" => "372",
            "code_telephone" => "353",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Israël",
            "name_en" => "Israel",
            "code_iso_2" => "IL",
            "code_iso_3" => "ISR",
            "code_numeric" => "376",
            "code_telephone" => "972",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Italie",
            "name_en" => "Italy",
            "code_iso_2" => "IT",
            "code_iso_3" => "ITA",
            "code_numeric" => "380",
            "code_telephone" => "39",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Côte d'Ivoire",
            "name_en" => "Côte d'Ivoire",
            "code_iso_2" => "CI",
            "code_iso_3" => "CIV",
            "code_numeric" => "384",
            "code_telephone" => "384",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Jamaïque",
            "name_en" => "Jamaica",
            "code_iso_2" => "JM",
            "code_iso_3" => "JAM",
            "code_numeric" => "388",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Japon",
            "name_en" => "Japan",
            "code_iso_2" => "JP",
            "code_iso_3" => "JPN",
            "code_numeric" => "392",
            "code_telephone" => "81",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Kazakhstan",
            "name_en" => "Kazakhstan",
            "code_iso_2" => "KZ",
            "code_iso_3" => "KAZ",
            "code_numeric" => "398",
            "code_telephone" => "7",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Jordanie",
            "name_en" => "Jordan",
            "code_iso_2" => "JO",
            "code_iso_3" => "JOR",
            "code_numeric" => "400",
            "code_telephone" => "962",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Kenya",
            "name_en" => "Kenya",
            "code_iso_2" => "KE",
            "code_iso_3" => "KEN",
            "code_numeric" => "404",
            "code_telephone" => "254",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Corée RPD",
            "name_en" => "Korea DPR",
            "code_iso_2" => "KP",
            "code_iso_3" => "PRK",
            "code_numeric" => "408",
            "code_telephone" => "850",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Corée",
            "name_en" => "Korea",
            "code_iso_2" => "KR",
            "code_iso_3" => "KOR",
            "code_numeric" => "410",
            "code_telephone" => "82",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Koweït",
            "name_en" => "Kuwait",
            "code_iso_2" => "KW",
            "code_iso_3" => "KWT",
            "code_numeric" => "414",
            "code_telephone" => "965",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Kirghizistan",
            "name_en" => "Kyrgyzstan",
            "code_iso_2" => "KG",
            "code_iso_3" => "KGZ",
            "code_numeric" => "417",
            "code_telephone" => "996",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Lao RDP",
            "name_en" => "Lao PDR",
            "code_iso_2" => "LA",
            "code_iso_3" => "LAO",
            "code_numeric" => "418",
            "code_telephone" => "856",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:34",
            "updated_at" => "2022-07-26 07:24:34",
        ),
        array(
            "name_fr" => "Liban",
            "name_en" => "Lebanon",
            "code_iso_2" => "LB",
            "code_iso_3" => "LBN",
            "code_numeric" => "422",
            "code_telephone" => "961",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Lesotho",
            "name_en" => "Lesotho",
            "code_iso_2" => "LS",
            "code_iso_3" => "LSO",
            "code_numeric" => "426",
            "code_telephone" => "426",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Lettonie",
            "name_en" => "Latvia",
            "code_iso_2" => "LV",
            "code_iso_3" => "LVA",
            "code_numeric" => "428",
            "code_telephone" => "371",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Libéria",
            "name_en" => "Liberia",
            "code_iso_2" => "LR",
            "code_iso_3" => "LBR",
            "code_numeric" => "430",
            "code_telephone" => "430",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Libye",
            "name_en" => "Lybia",
            "code_iso_2" => "LY",
            "code_iso_3" => "LBY",
            "code_numeric" => "434",
            "code_telephone" => "218",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Liechtenstein",
            "name_en" => "Liechtenstein",
            "code_iso_2" => "LI",
            "code_iso_3" => "LIE",
            "code_numeric" => "438",
            "code_telephone" => "423",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Lituanie",
            "name_en" => "Lithuania",
            "code_iso_2" => "LT",
            "code_iso_3" => "LTU",
            "code_numeric" => "440",
            "code_telephone" => "370",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Luxembourg",
            "name_en" => "Luxembourg",
            "code_iso_2" => "LU",
            "code_iso_3" => "LUX",
            "code_numeric" => "442",
            "code_telephone" => "352",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Macao",
            "name_en" => "Macao",
            "code_iso_2" => "MO",
            "code_iso_3" => "MAC",
            "code_numeric" => "446",
            "code_telephone" => "853",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Madagascar",
            "name_en" => "Madagascar",
            "code_iso_2" => "MG",
            "code_iso_3" => "MDG",
            "code_numeric" => "450",
            "code_telephone" => "261",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:35",
            "updated_at" => "2022-07-26 07:24:35",
        ),
        array(
            "name_fr" => "Malawi",
            "name_en" => "Malawi",
            "code_iso_2" => "MW",
            "code_iso_3" => "MWI",
            "code_numeric" => "454",
            "code_telephone" => "265",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Malaisie",
            "name_en" => "Malaysia",
            "code_iso_2" => "MY",
            "code_iso_3" => "MYS",
            "code_numeric" => "458",
            "code_telephone" => "60",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Maldives",
            "name_en" => "Maldives",
            "code_iso_2" => "MV",
            "code_iso_3" => "MDV",
            "code_numeric" => "462",
            "code_telephone" => "960",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Mali",
            "name_en" => "Mali",
            "code_iso_2" => "ML",
            "code_iso_3" => "MLI",
            "code_numeric" => "466",
            "code_telephone" => "466",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Malte",
            "name_en" => "Malta",
            "code_iso_2" => "MT",
            "code_iso_3" => "MLT",
            "code_numeric" => "470",
            "code_telephone" => "356",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Martinique",
            "name_en" => "Martinique",
            "code_iso_2" => "MQ",
            "code_iso_3" => "MTQ",
            "code_numeric" => "474",
            "code_telephone" => "596",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Mauritanie",
            "name_en" => "Mauritania",
            "code_iso_2" => "MR",
            "code_iso_3" => "MRT",
            "code_numeric" => "478",
            "code_telephone" => "222",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Maurice",
            "name_en" => "Mauritius",
            "code_iso_2" => "MU",
            "code_iso_3" => "MUS",
            "code_numeric" => "480",
            "code_telephone" => "230",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Mexique",
            "name_en" => "Mexico",
            "code_iso_2" => "MX",
            "code_iso_3" => "MEX",
            "code_numeric" => "484",
            "code_telephone" => "52",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Monaco",
            "name_en" => "Monaco",
            "code_iso_2" => "MC",
            "code_iso_3" => "MCO",
            "code_numeric" => "492",
            "code_telephone" => "377",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Mongolie",
            "name_en" => "Mongolia",
            "code_iso_2" => "MN",
            "code_iso_3" => "MNG",
            "code_numeric" => "496",
            "code_telephone" => "976",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Moldova",
            "name_en" => "Moldova",
            "code_iso_2" => "MD",
            "code_iso_3" => "MDA",
            "code_numeric" => "498",
            "code_telephone" => "373",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:36",
            "updated_at" => "2022-07-26 07:24:36",
        ),
        array(
            "name_fr" => "Monténégro",
            "name_en" => "Montenegro",
            "code_iso_2" => "ME",
            "code_iso_3" => "MNE",
            "code_numeric" => "499",
            "code_telephone" => "382",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Montserrat",
            "name_en" => "Montserrat",
            "code_iso_2" => "MS",
            "code_iso_3" => "MSR",
            "code_numeric" => "500",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Maroc",
            "name_en" => "Morocco",
            "code_iso_2" => "MA",
            "code_iso_3" => "MAR",
            "code_numeric" => "504",
            "code_telephone" => "212",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Mozambique",
            "name_en" => "Mozambique",
            "code_iso_2" => "MZ",
            "code_iso_3" => "MOZ",
            "code_numeric" => "508",
            "code_telephone" => "258",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Oman",
            "name_en" => "Oman",
            "code_iso_2" => "OM",
            "code_iso_3" => "OMN",
            "code_numeric" => "512",
            "code_telephone" => "968",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Namibie",
            "name_en" => "Namibia",
            "code_iso_2" => "NA",
            "code_iso_3" => "NAM",
            "code_numeric" => "516",
            "code_telephone" => "264",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Nauru",
            "name_en" => "Nauru",
            "code_iso_2" => "NR",
            "code_iso_3" => "NRU",
            "code_numeric" => "520",
            "code_telephone" => "674",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Népal",
            "name_en" => "Nepal",
            "code_iso_2" => "NP",
            "code_iso_3" => "NPL",
            "code_numeric" => "524",
            "code_telephone" => "977",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Pays-Bas",
            "name_en" => "Netherlands",
            "code_iso_2" => "NL",
            "code_iso_3" => "NLD",
            "code_numeric" => "528",
            "code_telephone" => "31",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Curaçao",
            "name_en" => "Curaçao",
            "code_iso_2" => "CW",
            "code_iso_3" => "CUW",
            "code_numeric" => "531",
            "code_telephone" => "599",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Aruba",
            "name_en" => "Aruba",
            "code_iso_2" => "AW",
            "code_iso_3" => "ABW",
            "code_numeric" => "533",
            "code_telephone" => "297",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Saint-Martin",
            "name_en" => "Sint Maarten",
            "code_iso_2" => "SX",
            "code_iso_3" => "SXM",
            "code_numeric" => "534",
            "code_telephone" => "599",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Bonaire, Saint-Eustache et Saba",
            "name_en" => "Bonaire, Sint Eustatius and Saba",
            "code_iso_2" => "BQ",
            "code_iso_3" => "BES",
            "code_numeric" => "535",
            "code_telephone" => "599",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:37",
            "updated_at" => "2022-07-26 07:24:37",
        ),
        array(
            "name_fr" => "Nouvelle-Calédonie",
            "name_en" => "New Caledonia",
            "code_iso_2" => "NC",
            "code_iso_3" => "NCL",
            "code_numeric" => "540",
            "code_telephone" => "687",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Vanuatu",
            "name_en" => "Vanuatu",
            "code_iso_2" => "VU",
            "code_iso_3" => "VUT",
            "code_numeric" => "548",
            "code_telephone" => "678",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Nouvelle-Zélande",
            "name_en" => "New Zealand",
            "code_iso_2" => "NZ",
            "code_iso_3" => "NZL",
            "code_numeric" => "554",
            "code_telephone" => "64",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Nicaragua",
            "name_en" => "Nicaragua",
            "code_iso_2" => "NI",
            "code_iso_3" => "NIC",
            "code_numeric" => "558",
            "code_telephone" => "505",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Niger",
            "name_en" => "Niger",
            "code_iso_2" => "NE",
            "code_iso_3" => "NER",
            "code_numeric" => "562",
            "code_telephone" => "227",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Nigéria",
            "name_en" => "Nigeria",
            "code_iso_2" => "NG",
            "code_iso_3" => "NGA",
            "code_numeric" => "566",
            "code_telephone" => "234",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Niue",
            "name_en" => "Niue",
            "code_iso_2" => "NU",
            "code_iso_3" => "NIU",
            "code_numeric" => "570",
            "code_telephone" => "683",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Norfolk",
            "name_en" => "Norfolk Island",
            "code_iso_2" => "NF",
            "code_iso_3" => "NFK",
            "code_numeric" => "574",
            "code_telephone" => "672",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Norvège",
            "name_en" => "Norway",
            "code_iso_2" => "NO",
            "code_iso_3" => "NOR",
            "code_numeric" => "578",
            "code_telephone" => "47",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Mariannes du Nord",
            "name_en" => "Northern Mariana Islands",
            "code_iso_2" => "MP",
            "code_iso_3" => "MNP",
            "code_numeric" => "580",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Îles mineures éloignées des États-Unis",
            "name_en" => "United States Minor Outlying Islands",
            "code_iso_2" => "UM",
            "code_iso_3" => "UMI",
            "code_numeric" => "581",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Micronésie EF",
            "name_en" => "Micronesia FS",
            "code_iso_2" => "FM",
            "code_iso_3" => "FSM",
            "code_numeric" => "583",
            "code_telephone" => "691",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Marshall",
            "name_en" => "Marshall Islands",
            "code_iso_2" => "MH",
            "code_iso_3" => "MHL",
            "code_numeric" => "584",
            "code_telephone" => "692",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Palaos",
            "name_en" => "Palau",
            "code_iso_2" => "PW",
            "code_iso_3" => "PLW",
            "code_numeric" => "585",
            "code_telephone" => "680",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Pakistan",
            "name_en" => "Pakistan",
            "code_iso_2" => "PK",
            "code_iso_3" => "PAK",
            "code_numeric" => "586",
            "code_telephone" => "92",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Panama",
            "name_en" => "Panama",
            "code_iso_2" => "PA",
            "code_iso_3" => "PAN",
            "code_numeric" => "591",
            "code_telephone" => "507",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:38",
            "updated_at" => "2022-07-26 07:24:38",
        ),
        array(
            "name_fr" => "Papouasie-Nouvelle-Guinée",
            "name_en" => "Papua New Guinea",
            "code_iso_2" => "PG",
            "code_iso_3" => "PNG",
            "code_numeric" => "598",
            "code_telephone" => "675",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Paraguay",
            "name_en" => "Paraguay",
            "code_iso_2" => "PY",
            "code_iso_3" => "PRY",
            "code_numeric" => "600",
            "code_telephone" => "595",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Pérou",
            "name_en" => "Peru",
            "code_iso_2" => "PE",
            "code_iso_3" => "PER",
            "code_numeric" => "604",
            "code_telephone" => "51",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Philippines",
            "name_en" => "Philippines",
            "code_iso_2" => "PH",
            "code_iso_3" => "PHL",
            "code_numeric" => "608",
            "code_telephone" => "63",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Pitcairn",
            "name_en" => "Pitcairn",
            "code_iso_2" => "PN",
            "code_iso_3" => "PCN",
            "code_numeric" => "612",
            "code_telephone" => "64",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Pologne",
            "name_en" => "Poland",
            "code_iso_2" => "PL",
            "code_iso_3" => "POL",
            "code_numeric" => "616",
            "code_telephone" => "48",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Portugal",
            "name_en" => "Portugal",
            "code_iso_2" => "PT",
            "code_iso_3" => "PRT",
            "code_numeric" => "620",
            "code_telephone" => "351",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Guinée-Bissau",
            "name_en" => "Guinea-Bissau",
            "code_iso_2" => "GW",
            "code_iso_3" => "GNB",
            "code_numeric" => "624",
            "code_telephone" => "245",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Timor-Leste",
            "name_en" => "Timor-Leste",
            "code_iso_2" => "TL",
            "code_iso_3" => "TLS",
            "code_numeric" => "626",
            "code_telephone" => "670",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Porto Rico",
            "name_en" => "Puerto Rico",
            "code_iso_2" => "PR",
            "code_iso_3" => "PRI",
            "code_numeric" => "630",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Qatar",
            "name_en" => "Qatar",
            "code_iso_2" => "QA",
            "code_iso_3" => "QAT",
            "code_numeric" => "634",
            "code_telephone" => "974",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Réunion",
            "name_en" => "Réunion",
            "code_iso_2" => "RE",
            "code_iso_3" => "REU",
            "code_numeric" => "638",
            "code_telephone" => "638",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Roumanie",
            "name_en" => "Romania",
            "code_iso_2" => "RO",
            "code_iso_3" => "ROU",
            "code_numeric" => "642",
            "code_telephone" => "40",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Russie",
            "name_en" => "Russia",
            "code_iso_2" => "RU",
            "code_iso_3" => "RUS",
            "code_numeric" => "643",
            "code_telephone" => "7",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Rwanda",
            "name_en" => "Rwanda",
            "code_iso_2" => "RW",
            "code_iso_3" => "RWA",
            "code_numeric" => "646",
            "code_telephone" => "250",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Saint-Barthélemy",
            "name_en" => "Saint Barthélemy",
            "code_iso_2" => "BL",
            "code_iso_3" => "BLM",
            "code_numeric" => "652",
            "code_telephone" => "590",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:39",
            "updated_at" => "2022-07-26 07:24:39",
        ),
        array(
            "name_fr" => "Sainte-Hélène, Ascension et Tristan da Cunha",
            "name_en" => "Saint Helena, Ascension and Tristan da Cunha",
            "code_iso_2" => "SH",
            "code_iso_3" => "SHN",
            "code_numeric" => "654",
            "code_telephone" => "290",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Saint-Kitts-et-Nevis",
            "name_en" => "Saint Kitts and Nevis",
            "code_iso_2" => "KN",
            "code_iso_3" => "KNA",
            "code_numeric" => "659",
            "code_telephone" => "869",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Anguilla",
            "name_en" => "Anguilla",
            "code_iso_2" => "AI",
            "code_iso_3" => "AIA",
            "code_numeric" => "660",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Sainte-Lucie",
            "name_en" => "Saint Lucia",
            "code_iso_2" => "LC",
            "code_iso_3" => "LCA",
            "code_numeric" => "662",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Saint-Martin",
            "name_en" => "Saint Martin",
            "code_iso_2" => "MF",
            "code_iso_3" => "MAF",
            "code_numeric" => "663",
            "code_telephone" => "590",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Saint-Pierre-et-Miquelon",
            "name_en" => "Saint Pierre and Miquelon",
            "code_iso_2" => "PM",
            "code_iso_3" => "SPM",
            "code_numeric" => "666",
            "code_telephone" => "508",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Saint-Vincent-et-les Grenadines",
            "name_en" => "Saint Vincent and the Grenadines",
            "code_iso_2" => "VC",
            "code_iso_3" => "VCT",
            "code_numeric" => "670",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Saint-Marin",
            "name_en" => "San Marino",
            "code_iso_2" => "SM",
            "code_iso_3" => "SMR",
            "code_numeric" => "674",
            "code_telephone" => "590",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Sao Tomé-et-Principe",
            "name_en" => "Sao Tome and Principe",
            "code_iso_2" => "ST",
            "code_iso_3" => "STP",
            "code_numeric" => "678",
            "code_telephone" => "239",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Arabie saoudite",
            "name_en" => "Saudi Arabia",
            "code_iso_2" => "SA",
            "code_iso_3" => "SAU",
            "code_numeric" => "682",
            "code_telephone" => "966",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Sénégal",
            "name_en" => "Senegal",
            "code_iso_2" => "SN",
            "code_iso_3" => "SEN",
            "code_numeric" => "686",
            "code_telephone" => "221",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Serbie",
            "name_en" => "Serbia",
            "code_iso_2" => "RS",
            "code_iso_3" => "SRB",
            "code_numeric" => "688",
            "code_telephone" => "381",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Seychelles",
            "name_en" => "Seychelles",
            "code_iso_2" => "SC",
            "code_iso_3" => "SYC",
            "code_numeric" => "690",
            "code_telephone" => "248",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Sierra Leone",
            "name_en" => "Sierra Leone",
            "code_iso_2" => "SL",
            "code_iso_3" => "SLE",
            "code_numeric" => "694",
            "code_telephone" => "232",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Singapour",
            "name_en" => "Singapore",
            "code_iso_2" => "SG",
            "code_iso_3" => "SGP",
            "code_numeric" => "702",
            "code_telephone" => "65",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Slovaquie",
            "name_en" => "Slovakia",
            "code_iso_2" => "SK",
            "code_iso_3" => "SVK",
            "code_numeric" => "703",
            "code_telephone" => "65",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:40",
            "updated_at" => "2022-07-26 07:24:40",
        ),
        array(
            "name_fr" => "Viet Nam",
            "name_en" => "Viet Nam",
            "code_iso_2" => "VN",
            "code_iso_3" => "VNM",
            "code_numeric" => "704",
            "code_telephone" => "84",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Slovénie",
            "name_en" => "Slovenia",
            "code_iso_2" => "SI",
            "code_iso_3" => "SVN",
            "code_numeric" => "705",
            "code_telephone" => "421",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Somalie",
            "name_en" => "Somalia",
            "code_iso_2" => "SO",
            "code_iso_3" => "SOM",
            "code_numeric" => "706",
            "code_telephone" => "252",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Afrique du Sud",
            "name_en" => "South Africa",
            "code_iso_2" => "ZA",
            "code_iso_3" => "ZAF",
            "code_numeric" => "710",
            "code_telephone" => "27",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Zimbabwe",
            "name_en" => "Zimbabwe",
            "code_iso_2" => "ZW",
            "code_iso_3" => "ZWE",
            "code_numeric" => "716",
            "code_telephone" => "263",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Espagne",
            "name_en" => "Spain",
            "code_iso_2" => "ES",
            "code_iso_3" => "ESP",
            "code_numeric" => "724",
            "code_telephone" => "34",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Soudan du Sud",
            "name_en" => "South Sudan",
            "code_iso_2" => "SS",
            "code_iso_3" => "SSD",
            "code_numeric" => "728",
            "code_telephone" => "211",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Soudan",
            "name_en" => "Sudan",
            "code_iso_2" => "SD",
            "code_iso_3" => "SDN",
            "code_numeric" => "729",
            "code_telephone" => "249",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Sahara occidental*",
            "name_en" => "Western Sahara",
            "code_iso_2" => "EH",
            "code_iso_3" => "ESH",
            "code_numeric" => "732",
            "code_telephone" => "597",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Suriname",
            "name_en" => "Suriname",
            "code_iso_2" => "SR",
            "code_iso_3" => "SUR",
            "code_numeric" => "740",
            "code_telephone" => "597",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Svalbard et l'Île Jan Mayen",
            "name_en" => "Svalbard and Jan Mayen",
            "code_iso_2" => "SJ",
            "code_iso_3" => "SJM",
            "code_numeric" => "744",
            "code_telephone" => "47",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Eswatini",
            "name_en" => "Eswatini",
            "code_iso_2" => "SZ",
            "code_iso_3" => "SWZ",
            "code_numeric" => "748",
            "code_telephone" => "268",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Suède",
            "name_en" => "Sweden",
            "code_iso_2" => "SE",
            "code_iso_3" => "SWE",
            "code_numeric" => "752",
            "code_telephone" => "46",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:41",
            "updated_at" => "2022-07-26 07:24:41",
        ),
        array(
            "name_fr" => "Suisse",
            "name_en" => "Switzerland",
            "code_iso_2" => "CH",
            "code_iso_3" => "CHE",
            "code_numeric" => "756",
            "code_telephone" => "41",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:42",
            "updated_at" => "2022-07-26 07:24:42",
        ),
        array(
            "name_fr" => "République arabe syrienne",
            "name_en" => "Syrian Arab Republic",
            "code_iso_2" => "SY",
            "code_iso_3" => "SYR",
            "code_numeric" => "760",
            "code_telephone" => "963",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:42",
            "updated_at" => "2022-07-26 07:24:42",
        ),
        array(
            "name_fr" => "Tadjikistan",
            "name_en" => "Tajikistan",
            "code_iso_2" => "TJ",
            "code_iso_3" => "TJK",
            "code_numeric" => "762",
            "code_telephone" => "992",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:42",
            "updated_at" => "2022-07-26 07:24:42",
        ),
        array(
            "name_fr" => "Thaïlande",
            "name_en" => "Thailand",
            "code_iso_2" => "TH",
            "code_iso_3" => "THA",
            "code_numeric" => "764",
            "code_telephone" => "66",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:42",
            "updated_at" => "2022-07-26 07:24:42",
        ),
        array(
            "name_fr" => "Togo",
            "name_en" => "Togo",
            "code_iso_2" => "TG",
            "code_iso_3" => "TGO",
            "code_numeric" => "768",
            "code_telephone" => "228",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:42",
            "updated_at" => "2022-07-26 07:24:42",
        ),
        array(
            "name_fr" => "Tokelau",
            "name_en" => "Tokelau",
            "code_iso_2" => "TK",
            "code_iso_3" => "TKL",
            "code_numeric" => "772",
            "code_telephone" => "690",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:42",
            "updated_at" => "2022-07-26 07:24:42",
        ),
        array(
            "name_fr" => "Tonga",
            "name_en" => "Tonga",
            "code_iso_2" => "TO",
            "code_iso_3" => "TON",
            "code_numeric" => "776",
            "code_telephone" => "676",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:42",
            "updated_at" => "2022-07-26 07:24:42",
        ),
        array(
            "name_fr" => "Trinité-et-Tobago",
            "name_en" => "Trinidad and Tobago",
            "code_iso_2" => "TT",
            "code_iso_3" => "TTO",
            "code_numeric" => "780",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:42",
            "updated_at" => "2022-07-26 07:24:42",
        ),
        array(
            "name_fr" => "Émirats arabes unis",
            "name_en" => "United Arab Emirates",
            "code_iso_2" => "AE",
            "code_iso_3" => "ARE",
            "code_numeric" => "784",
            "code_telephone" => "971",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:42",
            "updated_at" => "2022-07-26 07:24:42",
        ),
        array(
            "name_fr" => "Tunisie",
            "name_en" => "Tunisia",
            "code_iso_2" => "TN",
            "code_iso_3" => "TUN",
            "code_numeric" => "788",
            "code_telephone" => "216",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Turquie",
            "name_en" => "Turkey",
            "code_iso_2" => "TR",
            "code_iso_3" => "TUR",
            "code_numeric" => "792",
            "code_telephone" => "90",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Turkménistan",
            "name_en" => "Turkmenistan",
            "code_iso_2" => "TM",
            "code_iso_3" => "TKM",
            "code_numeric" => "795",
            "code_telephone" => "993",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Turks-et-Caïcos",
            "name_en" => "Turks and Caicos Islands",
            "code_iso_2" => "TC",
            "code_iso_3" => "TCA",
            "code_numeric" => "796",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Tuvalu",
            "name_en" => "Tuvalu",
            "code_iso_2" => "TV",
            "code_iso_3" => "TUV",
            "code_numeric" => "798",
            "code_telephone" => "688",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Ouganda",
            "name_en" => "Uganda",
            "code_iso_2" => "UG",
            "code_iso_3" => "UGA",
            "code_numeric" => "800",
            "code_telephone" => "256",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Ukraine",
            "name_en" => "Ukraine",
            "code_iso_2" => "UA",
            "code_iso_3" => "UKR",
            "code_numeric" => "804",
            "code_telephone" => "380",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Macédoine du Nord",
            "name_en" => "North Macedonia",
            "code_iso_2" => "MK",
            "code_iso_3" => "MKD",
            "code_numeric" => "807",
            "code_telephone" => "389",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Égypte",
            "name_en" => "Egypt",
            "code_iso_2" => "EG",
            "code_iso_3" => "EGY",
            "code_numeric" => "818",
            "code_telephone" => "20",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
            "name_en" => "United Kingdom of Great Britain and Northern Ireland",
            "code_iso_2" => "GB",
            "code_iso_3" => "GBR",
            "code_numeric" => "826",
            "code_telephone" => "44",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:43",
            "updated_at" => "2022-07-26 07:24:43",
        ),
        array(
            "name_fr" => "Guernesey",
            "name_en" => "Guernsey",
            "code_iso_2" => "GG",
            "code_iso_3" => "GGY",
            "code_numeric" => "831",
            "code_telephone" => "44",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Jersey",
            "name_en" => "Jersey",
            "code_iso_2" => "JE",
            "code_iso_3" => "JEY",
            "code_numeric" => "832",
            "code_telephone" => "44",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Île de Man",
            "name_en" => "Isle of Man",
            "code_iso_2" => "IM",
            "code_iso_3" => "IMN",
            "code_numeric" => "833",
            "code_telephone" => "44",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Tanzanie",
            "name_en" => "Tanzania",
            "code_iso_2" => "TZ",
            "code_iso_3" => "TZA",
            "code_numeric" => "834",
            "code_telephone" => "255",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "États-Unis d'Amérique",
            "name_en" => "united States of America",
            "code_iso_2" => "US",
            "code_iso_3" => "USA",
            "code_numeric" => "840",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Vierges des États-Unis",
            "name_en" => "Virgin Islands",
            "code_iso_2" => "VI",
            "code_iso_3" => "VIR",
            "code_numeric" => "850",
            "code_telephone" => "1",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Burkina Faso",
            "name_en" => "Burkina Faso",
            "code_iso_2" => "BF",
            "code_iso_3" => "BFA",
            "code_numeric" => "854",
            "code_telephone" => "226",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Uruguay",
            "name_en" => "Uruguay",
            "code_iso_2" => "UY",
            "code_iso_3" => "URY",
            "code_numeric" => "858",
            "code_telephone" => "598",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Ouzbékistan",
            "name_en" => "Uzbekistan",
            "code_iso_2" => "UZ",
            "code_iso_3" => "UZB",
            "code_numeric" => "860",
            "code_telephone" => "998",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Venezuela",
            "name_en" => "Venezuela",
            "code_iso_2" => "VE",
            "code_iso_3" => "VEN",
            "code_numeric" => "862",
            "code_telephone" => "58",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Wallis-et-Futuna",
            "name_en" => "Wallis and Futuna",
            "code_iso_2" => "WF",
            "code_iso_3" => "WLF",
            "code_numeric" => "876",
            "code_telephone" => "681",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Samoa",
            "name_en" => "Samoa",
            "code_iso_2" => "WS",
            "code_iso_3" => "WSM",
            "code_numeric" => "882",
            "code_telephone" => "685",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Yémen",
            "name_en" => "Yemen",
            "code_iso_2" => "YE",
            "code_iso_3" => "YEM",
            "code_numeric" => "887",
            "code_telephone" => "967",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
        array(
            "name_fr" => "Zambie",
            "name_en" => "Zambia",
            "code_iso_2" => "ZM",
            "code_iso_3" => "ZMB",
            "code_numeric" => "894",
            "code_telephone" => "260",
            "active" => 0,
            "created_at" => "2022-07-26 07:24:44",
            "updated_at" => "2022-07-26 07:24:44",
        ),
    );
}

?>