# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create test file and build directory
        run: |
          echo "Creating file..."
          echo "This is a test file." > test_file.txt
          echo "File created successfully."
          mkdir -p build
          echo "Build directory created."
          touch build/test1_file.txt
          echo "Test file in build directory created."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check if file exists
        run: test -f build/test1_file.txt
